// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTmz_1lLzdIgGW3W_-iF5jw3grK8OmiV0',
    appId: '1:169047432390:web:9746f803e08006a7e48bc7',
    messagingSenderId: '169047432390',
    projectId: 'share-stuff-8ac40',
    authDomain: 'share-stuff-8ac40.firebaseapp.com',
    storageBucket: 'share-stuff-8ac40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWdKuz2XLZhisx_jGn1fiawsJPFmBdMvM',
    appId: '1:169047432390:android:fcde123c843f5c57e48bc7',
    messagingSenderId: '169047432390',
    projectId: 'share-stuff-8ac40',
    storageBucket: 'share-stuff-8ac40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonbXrGK8ByuHHrOQT38DFzPzBAsFTGLk',
    appId: '1:169047432390:ios:64b7334f3cc33a90e48bc7',
    messagingSenderId: '169047432390',
    projectId: 'share-stuff-8ac40',
    storageBucket: 'share-stuff-8ac40.appspot.com',
    iosClientId: '169047432390-o7j9h26q7hpuvkel15m8k9ovdnn9kt6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareStuff',
  );
}
